github.com:
    users:
        Chanadu:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Chanadu
