github.com:
    users:
        Chanadu:
            oauth_token: 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
    git_protocol: https
    user: Chanadu
    oauth_token: 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
