github.com:
    users:
        Chanadu:
            oauth_token: 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
    git_protocol: https
    user: Chanadu
    oauth_token: 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
